apiVersion: batch/v1
kind: CronJob
metadata:
  name: client-cronjob
spec:
  schedule: "*/5 * * * *"  # This schedule runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: client
            image: manuelbcd/test-client:1.1
            imagePullPolicy: Always
            args:
            - "http://playground:80/etc/shadow"
          restartPolicy: OnFailure
