# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Sysdig - Build, scan, push and upload sarif report

on: workflow_dispatch

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Image is already published in dockerhub

    - name: Download SCA Resolver
      run: |
        wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
        tar -xzvf ScaResolver-linux64.tar.gz
        rm -rf ScaResolver-linux64.tar.gz

    - name: Install Maven, NPM, ... # Add any necessary package management
      run: |
        sudo apt install maven npm

    - name: Run Checkmarx One CLI Scan
      run: |
        ./ScaResolver -s /Users/DemoUser/scan_ecr_image -n DemoImageScan \
          -a Checkmarx -u jack -p '${{ secrets.CHECKMARX_PASSWORD }}' \
          --scan-containers --images “manuelbcd/security-playground:1.0.6”
